# -*- coding: utf-8 -*-
"""Youtube.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10DgyLM2JahuQ6pqNZprmp4gzjiR8sL8r
"""

!pip install pytube

!pip install jinja2

from pytube import YouTube
from jinja2 import Template

# Function to get video details
def get_video_details(video_url):
    try:
        yt = YouTube(video_url)
        return yt
    except Exception as e:
        print("An error occurred:", str(e))
        return None

# Example usage to get video details
video_url = input("Paste the YouTube video link: ")
video = get_video_details(video_url)

if video:
    # Generate the HTML template
    template = Template('''
    <html>
    <head>
        <title>{{ video_title }}</title>
    </head>
    <body>
        <h1>{{ video_title }}</h1>
        <p>{{ video_description }}</p>
        <h2>Channel: {{ channel_name }}</h2>
        <p>Length (seconds): {{ video_length }}</p>
        <p>Age Restricted: {{ video_age_restricted }}</p>
        <p>Captions: {{ video_captions }}</p>
        <p>Keywords: {{ video_keywords }}</p>
        <p>Views: {{ video_views }}</p>
    </body>
    </html>
    ''')

    # Render the template with the data
    rendered_html = template.render(
        video_title=video.title,
        video_description=video.description,
        channel_name=video.author,
        video_length=video.length,
        video_age_restricted=video.age_restricted,
        video_captions=video.captions,
        video_keywords=video.keywords,
        video_views=video.views
    )

    # Save the rendered HTML to a file
    with open('output.html', 'w', encoding='utf-8') as file:
        file.write(rendered_html)

    print("HTML file generated successfully.")
else:
    print("Invalid YouTube video link.")